version: 2

jobs:
  dev-plan-apply:
    # working_directory: /terraform-circle-ci-s3
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: change directory
          command: cd environments/dev-env/
      - run:          
          name: terraform init & plan
          command: |
            terraform init && terraform plan -out tfplan
      - run:            
          name: terraform apply
          command: |
            terraform apply -auto-approve tfplan            
      - persist_to_workspace:
          root: .
          paths:
            - .

  prod-plan:
    working_directory: /terraform-circle-ci-s3
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: change directory
          command: cd environments/prod-env/
      - run:          
          name: terraform init & plan
          command: |
            terraform init && terraform plan -out tfplan           
      - persist_to_workspace:
          root: .
          paths:
            - .

  prod-apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: change directory
          command: cd environments/prod-env/  
      - run:            
          name: terraform
          command: |
            terraform apply -auto-approve tfplan
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - dev-plan-apply
      - prod-plan
      - prod-apply:
          type: approval     
          requires:
            - prod-plan